-- AlterTable
ALTER TABLE "EuroNorm" ADD COLUMN     "group" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Hub" ADD COLUMN     "simMaxAge" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "simMaxAgeForBonus" INTEGER NOT NULL DEFAULT 7,
ADD COLUMN     "simMaxKm" INTEGER NOT NULL DEFAULT 200000,
ADD COLUMN     "simMaxKmForBonus" INTEGER NOT NULL DEFAULT 140000,
ADD COLUMN     "simMinEcoScoreForBonus" INTEGER NOT NULL DEFAULT 65,
ADD COLUMN     "simMinEuroNormGroupDiesel" INTEGER NOT NULL DEFAULT 5;

-- AlterTable
ALTER TABLE "Simulation" ADD COLUMN     "seats" INTEGER NOT NULL DEFAULT 0;
