import { PrismaClient } from '@/storage/client/client';

const CAR_BRANDS: { code: string; name: string }[] = [
  { code: 'abarth', name: 'Abarth' },
  { code: 'aiways', name: 'Aiways' },
  { code: 'alfa-romeo', name: 'Alfa Romeo' },
  { code: 'alpina', name: 'Alpina' },
  { code: 'alpine', name: 'Alpine' },
  { code: 'aston-martin', name: 'Aston Martin' },
  { code: 'audi', name: 'Audi' },
  { code: 'baic', name: 'BAIC' },
  { code: 'bentley', name: 'Bentley' },
  { code: 'bmw', name: 'BMW' },
  { code: 'bugatti', name: 'Bugatti' },
  { code: 'byd', name: 'BYD' },
  { code: 'cadillac', name: 'Cadillac' },
  { code: 'caterham', name: 'Caterham' },
  { code: 'changan', name: 'Changan' },
  { code: 'chevrolet', name: 'Chevrolet' },
  { code: 'chrysler', name: 'Chrysler' },
  { code: 'citroen', name: 'Citroën' },
  { code: 'cupra', name: 'Cupra' },
  { code: 'dacia', name: 'Dacia' },
  { code: 'daewoo', name: 'Daewoo' },
  { code: 'daihatsu', name: 'Daihatsu' },
  { code: 'dfsk', name: 'DFSK' },
  { code: 'dodge', name: 'Dodge' },
  { code: 'dongfeng', name: 'Dongfeng' },
  { code: 'donkervoort', name: 'Donkervoort' },
  { code: 'ds', name: 'DS' },
  { code: 'ferrari', name: 'Ferrari' },
  { code: 'fiat', name: 'Fiat' },
  { code: 'firefly', name: 'Firefly' },
  { code: 'fisker', name: 'Fisker' },
  { code: 'ford', name: 'Ford' },
  { code: 'forthing', name: 'Forthing' },
  { code: 'genesis', name: 'Genesis' },
  { code: 'gm-daewoo', name: 'GM Daewoo' },
  { code: 'honda', name: 'Honda' },
  { code: 'hongqi', name: 'Hongqi' },
  { code: 'hummer', name: 'Hummer' },
  { code: 'hyundai', name: 'Hyundai' },
  { code: 'infiniti', name: 'Infiniti' },
  { code: 'isuzu', name: 'Isuzu' },
  { code: 'jac', name: 'JAC' },
  { code: 'jaecoo', name: 'Jaecoo' },
  { code: 'jaguar', name: 'Jaguar' },
  { code: 'jeep', name: 'Jeep' },
  { code: 'kgm', name: 'KGM' },
  { code: 'kia', name: 'Kia' },
  { code: 'lada', name: 'Lada' },
  { code: 'lamborghini', name: 'Lamborghini' },
  { code: 'lancia', name: 'Lancia' },
  { code: 'land-rover', name: 'Land Rover' },
  { code: 'leapmotor', name: 'Leapmotor' },
  { code: 'levc', name: 'LEVC' },
  { code: 'lexus', name: 'Lexus' },
  { code: 'lightyear', name: 'Lightyear' },
  { code: 'lotus', name: 'Lotus' },
  { code: 'lucid', name: 'Lucid' },
  { code: 'lynk-co', name: 'Lynk & Co' },
  { code: 'man', name: 'MAN' },
  { code: 'maserati', name: 'Maserati' },
  { code: 'maybach', name: 'Maybach' },
  { code: 'maxus', name: 'Maxus' },
  { code: 'mazda', name: 'Mazda' },
  { code: 'mclaren', name: 'McLaren' },
  { code: 'mercedes-benz', name: 'Mercedes-Benz' },
  { code: 'mg', name: 'MG' },
  { code: 'mini', name: 'MINI' },
  { code: 'mitsubishi', name: 'Mitsubishi' },
  { code: 'morgan', name: 'Morgan' },
  { code: 'nio', name: 'NIO' },
  { code: 'nissan', name: 'Nissan' },
  { code: 'omoda', name: 'Omoda' },
  { code: 'opel', name: 'Opel' },
  { code: 'peugeot', name: 'Peugeot' },
  { code: 'polestar', name: 'Polestar' },
  { code: 'porsche', name: 'Porsche' },
  { code: 'renault', name: 'Renault' },
  { code: 'rimac', name: 'Rimac' },
  { code: 'rolls-royce', name: 'Rolls-Royce' },
  { code: 'rover', name: 'Rover' },
  { code: 'saab', name: 'Saab' },
  { code: 'seat', name: 'Seat' },
  { code: 'seres', name: 'Seres' },
  { code: 'skoda', name: 'Skoda' },
  { code: 'smart', name: 'Smart' },
  { code: 'ssangyong', name: 'SsangYong' },
  { code: 'subaru', name: 'Subaru' },
  { code: 'suzuki', name: 'Suzuki' },
  { code: 'swm', name: 'SWM' },
  { code: 'tesla', name: 'Tesla' },
  { code: 'toyota', name: 'Toyota' },
  { code: 'vinfast', name: 'Vinfast' },
  { code: 'volkswagen', name: 'Volkswagen' },
  { code: 'volvo', name: 'Volvo' },
  { code: 'voyah', name: 'Voyah' },
  { code: 'xpeng', name: 'Xpeng' },
  { code: 'zeekr', name: 'Zeekr' },
];

const LOCALES = ['en', 'nl', 'fr'] as const;

export async function seedCarBrands(prisma: PrismaClient) {
  console.log('Seeding car brands...');

  for (const cb of CAR_BRANDS) {
    const translations = LOCALES.map((locale) => ({ locale, name: cb.name }));
    await prisma.carBrand.upsert({
      where: { code: cb.code },
      update: {
        isActive: true,
        translations: {
          deleteMany: {},
          createMany: { data: translations },
        },
      },
      create: {
        code: cb.code,
        isActive: true,
        translations: {
          createMany: { data: translations },
        },
      },
    });
    console.log(`  Seeded: ${cb.code}`);
  }

  console.log('Car brand seeding complete.');
}
