import {
  CarOnboarding,
  CarOnboardingCarValueStatus,
  CarOnboardingInPreparationStatus,
  CarOnboardingInfoSessionStatus,
  CarOnboardingInsurerStatus,
  CarOnboardingRoadAssistancePlanStatus,
} from '@/domain/car-onboarding.model';

export const carOnboarding = (data: Partial<CarOnboarding> = {}): CarOnboarding => {
  return {
    id: data.id ?? '550e8400-e29b-41d4-a716-446655440000',
    street: data.street !== undefined ? data.street : null,
    town: data.town !== undefined ? data.town : null,
    phone: data.phone !== undefined ? data.phone : null,
    brand: data.brand !== undefined ? data.brand : null,
    fuelType: data.fuelType !== undefined ? data.fuelType : null,
    carType: data.carType !== undefined ? data.carType : null,
    carTypeOther: data.carTypeOther !== undefined ? data.carTypeOther : null,
    isPurchased: data.isPurchased ?? false,
    purchasePrice: data.purchasePrice ?? 0,
    carValue: data.carValue ?? 0,
    carValueCounterProposal: data.carValueCounterProposal ?? 0,
    carValueCounterProposalMessage: data.carValueCounterProposalMessage !== undefined ? data.carValueCounterProposalMessage : null,
    carValueStatus: data.carValueStatus ?? CarOnboardingCarValueStatus.TODO,
    hasInsuranceContract: data.hasInsuranceContract ?? false,
    insurer: data.insurer !== undefined ? data.insurer : null,
    insurerStatus: data.insurerStatus ?? CarOnboardingInsurerStatus.TODO,
    insurerContractStartedAt: data.insurerContractStartedAt !== undefined ? data.insurerContractStartedAt : null,
    hasExistingRoadAssistancePlan: data.hasExistingRoadAssistancePlan ?? false,
    existingRoadAssistancePlanEndDate: data.existingRoadAssistancePlanEndDate !== undefined ? data.existingRoadAssistancePlanEndDate : null,
    roadAssistancePlan: data.roadAssistancePlan !== undefined ? data.roadAssistancePlan : null,
    roadAssistancePlanStatus: data.roadAssistancePlanStatus ?? CarOnboardingRoadAssistancePlanStatus.TODO,
    infoSessionDate: data.infoSessionDate !== undefined ? data.infoSessionDate : null,
    infoSessionPcId: data.infoSessionPcId !== undefined ? data.infoSessionPcId : null,
    infoSessionStatus: data.infoSessionStatus ?? CarOnboardingInfoSessionStatus.TODO,
    depreciationCostKm: data.depreciationCostKm ?? 0,
    isNewCar: data.isNewCar ?? false,
    mileage: data.mileage ?? 0,
    vin: data.vin !== undefined ? data.vin : null,
    plate: data.plate !== undefined ? data.plate : null,
    firstRegisteredAt: data.firstRegisteredAt !== undefined ? data.firstRegisteredAt : null,
    seats: data.seats ?? 0,
    isVan: data.isVan ?? false,
    owner: data.owner !== undefined ? data.owner : null,
    simulation: data.simulation !== undefined ? data.simulation : null,
    registrationCertificateFront: data.registrationCertificateFront !== undefined ? data.registrationCertificateFront : null,
    registrationCertificateBack: data.registrationCertificateBack !== undefined ? data.registrationCertificateBack : null,
    inspectionCertificate: data.inspectionCertificate !== undefined ? data.inspectionCertificate : null,
    pinkForm: data.pinkForm !== undefined ? data.pinkForm : null,
    statusInPreparation: data.statusInPreparation ?? CarOnboardingInPreparationStatus.OPEN,
    createdAt: data.createdAt ?? new Date(),
    updatedAt: data.updatedAt ?? new Date(),
  };
};

export const completeCarOnboarding = (data: Partial<CarOnboarding> = {}): CarOnboarding => {
  return carOnboarding({
    street: 'Main Street 1',
    town: { id: '550e8400-e29b-41d4-a716-446655440099', name: '1000 Brussels' },
    phone: '+32 470 00 00 00',
    brand: { id: '550e8400-e29b-41d4-a716-446655440001', name: 'Audi' },
    fuelType: { id: '550e8400-e29b-41d4-a716-446655440002', name: 'Diesel' },
    carType: { id: '550e8400-e29b-41d4-a716-446655440003', name: 'A4' },
    registrationCertificateFront: { id: '550e8400-e29b-41d4-a716-446655440020', name: 'registration-front.jpg' },
    registrationCertificateBack: { id: '550e8400-e29b-41d4-a716-446655440021', name: 'registration-back.jpg' },
    owner: { id: '550e8400-e29b-41d4-a716-446655440098', hasPlayConnector: true },
    carValueStatus: CarOnboardingCarValueStatus.RESOLVED,
    insurer: { id: '550e8400-e29b-41d4-a716-446655440010', name: 'AXA' },
    hasInsuranceContract: true,
    insurerStatus: CarOnboardingInsurerStatus.READY,
    insurerContractStartedAt: new Date('2020-01-15'),
    roadAssistancePlan: { id: '550e8400-e29b-41d4-a716-446655440011', name: 'Basic' },
    hasExistingRoadAssistancePlan: false,
    roadAssistancePlanStatus: CarOnboardingRoadAssistancePlanStatus.READY,
    infoSessionDate: new Date('2026-06-20T09:25:00'),
    infoSessionPcId: '1359',
    infoSessionStatus: CarOnboardingInfoSessionStatus.DONE,
    ...data,
  });
};
